{{- if eq .Values.workloadType "DaemonSet" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "foldingathome.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "foldingathome.name" . }}
    helm.sh/chart: {{ include "foldingathome.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "foldingathome.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "foldingathome.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if .Values.runOnMaster }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts: # Mount config.xml file
          - name: fah-config
            mountPath: /etc/fahclient/config.xml
            subPath: config.xml   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}         
      volumes:
        - name: fah-config
          configMap:
            name: {{ include "foldingathome.fullname" . }}
{{- if .Values.priorityClassName }}
      priorityClassName: low-priority-class
{{- end }}
{{- end }}